type: match_pairs
visible: false
header: Table of Integrals
text: |
  Match functions with their indefinite integrals.

  And memorize them. 

  By heart. 

  All of them. 

  No excuses.
shuffle: true
score: 1
quiz:
  left:
    - text: |
        $$\int\alpha \ dx$$
    - text: |
        $$\int x^k \ dx$$
    - text: |
        $$\int \frac{dx}{x} $$
    - text: |
        $$\int e^x dx$$
    - text: |
        $$\int \cos x \ dx$$
    - text: |
        $$\int \sin x \ dx$$
    - text: |
        $$\int \frac{dx}{\cos^2 x}$$
    - text: |
        $$\int \frac{dx}{\sin^2x}$$
    - text: |
        $$\int \frac{dx}{\sqrt{1 - x^2}}$$
    - text: |
        $$\int \frac{dx}{1 + x^2}$$
    - text: |
        $$\int \frac{dx}{x^2 - 1}$$
    - text: |
        $$\int \frac{dx}{\sqrt{x^2 \pm 1}}$$
    - text: |
        $$\int_{x_0}^x f'(x) dx $$
    - text: |
        $$\int_{x_0}^{x_2} f(x) dx $$
    - text: |
        $$\int \left[f(x) + g(x)\right] dx$$
    - text: |
        $$\int \alpha \ f(x) dx$$
    - text: |
        $$\int_{x_0}^{x_1} f(x) dx$$
    - text:
        $$\int f(x)\ dg(x)$$
  variants:
    - text: |
        $$\alpha x + C$$
    - text: |
        $$\frac{x^{k+1}}{k + 1} + C$$
    - text: |
        $$\ln |x| + C$$
    - text: |
        $$e^x + C$$
    - text: |
        $$\sin x + C$$
    - text: |
        $$- \cos x + C$$
    - text: |
        $$\tg x + C$$
    - text: |
        $$\ctg x + C$$
    - text: |
        $$\arcsin x + C$$
    - text: |
        $$\mathrm{arctg} x + C$$
    - text: |
        $$\frac{1}{2} \ln \left|\frac{x - 1}{x + 1}\right| + C$$
    - text: |
        $$\ln \left|x + \sqrt{x^2 \pm 1}\right| + C$$
    - text: |
        $$f(x) + C$$
    - text: |
        $$\int_{x_0}^{x_1} f(x) \ dx +  \int_{x_1}^{x_2} f(x) \ dx$$
    - text: |
        $$\int f(x) dx + \int g(x) dx$$
    - text: |
        $$\alpha \int f(x) dx $$
    - text: |
        $$-\int_{x_1}^{x_0} f(x) dx $$
    - text: |
        $$f(x)g(x) - \int g(x) df(x)$$
