type: order_cards
visible: false
header: Derivative of Sinus
text: Order cards to get proof of derivative of sinus
shuffle: true
score: 1
quiz:
  variants:
    - text: >
        Take derivative of a function and insert $f(x) = \sin (x)$:

        $$\frac{d f(x)}{dx} = \frac{f(x + dx) - f(x)}{dx} = \frac{\sin(x + dx) -
        \sin(x)}{dx}$$
    - text: |
        Use trigonometric identity:
        $$\sin(a + b) = \sin(a) \cos(b) + \cos(a) \sin(b)$$
        to expand the first term in the enumerator.
    - text: |
        Expaning first term in the enumerator:
        $$\frac{\sin(x) \cos(dx) + \cos(x) \sin(dx) - \sin(x)}{dx}$$
    - text: |
        Firstly, for small values of $dx$: 
        $$\sin(dx) \approx dx$$
    - text: >
        Secondly, for small values of $dx$ (due to the same reason): 

        $$\cos(dx) = \sqrt{1 - \sin^2 dx} \approx \sqrt{1 - dx^2} \approx 1 -
        \frac{dx^2}{2}$$
    - text: |
        Substitute the approximations into the expression:
        $$\frac{\sin(x) (1 - \frac{dx^2}{2}) + \cos(x) dx - \sin(x)}{dx}$$
    - text: |
        Simplify the expression:
        $$\frac{\sin(x) - \frac{dx^2}{2} \sin(x) + \cos(x) dx - \sin(x)}{dx}$$
    - text: |
        The first and the last term cancels:
        $$\frac{- \frac{dx^2}{2} \sin(x) + \cos(x) dx}{dx}$$
    - text: |
        $dx$ in enumerator and in denominator cancels:
        $$- \frac{dx}{2} \sin(x) + \cos(x)$$
    - text: |
        For small values of $dx$ first term is negligible:
        $$\cos(x)$$
    - text: |
        So, the derivative of $\sin(x)$ is $\cos(x)$:
        $$\frac{d \sin(x)}{dx} = \cos(x)$$
